language: c
compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "hXw0ihwYweqPYW1a2kPo9XwvtECQbbjr3RjT58oTCJiSGnSAoKXiPx91gzjfCbTe21yHm+bDbS8MZ1t27K5FX4+bGJJYUE/WWEt+3zsgbGdoZ0CobVCysGCCdR0YXJFEozqLAKcAiJoQAXzMA+uuoYjU4o6iItiao4hHw198uebfIbdv7tH05Z7wGuvrRO+A8wsxMaLoG2Pz7YEzxd+ONkQ6eVMMozQ5Pi8Dg3qamHzQ0qF9mXaimGxmkWK/wok5Wskdyvlk6P+iYugWKhMdIcDsFka1g4LC5PtD2HaQm/vrOzyroa95HzWVrl35zYDtQiGgXT3ufbp9gJp/Rx19KiGfOEEe+JHO4Aam6g70JCOP/9Vftio6l3NSNQp6nP8nGZ4KGDTmNsa4hqNSHMvIvbXrxabrk2ovKKb+fy2ikzhgd2FAvrKzsw6Qzs6IJUfKnuXmeegMnddLUzY3BOow30pZ5VFp1dyU05ElyLqp5E6cYSGDIPKqWl/5fQFiKwBB7F7wnFAVVkamKkP6JhVXIxaZ+17zX+E7xZZdmVez4r4gss2klpMgHbWF0G8Dbsu2iwWiDKXFB7wA3os2d2JPpO4fgsQGH3RwgNua0/IDYIfSyun7/Tn4SNc9F/vl3QZq64O6okT8dn0y8iyIHu+hrpXsI72xhhFz8q96RKShPhM="

branches:
  only:
    - sisyphus

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

install:
  - sudo apt-get install scons

script:
  - scons

addons:
  coverity_scan:
    project:
      name: "Etersoft/libnss-role"
      description: "NSS API library and admin tools for roles and privilegies"
    notification_email: lav@etersoft.ru
    build_command_prepend: 
    build_command: scons
    branch_pattern: coverity_scan
