language: c
compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "MQ9Q5cvFggoZOYP6/kVYRwR731v4BNKlCEm5VSo4aPdPPpNFRyJyBm0RRlVB68AEHGYm2p5v2AM8BhMbzVYwo7q+Yb7IIdaOJXmPS9UdN2nF1T2KqfhHkblcbH0Z2zk1Ym+R+S5mbS1Gg59JlXoYT0A0MGQIbSkIoABRD2SM4UPq1bchoftd8JzXPJgZLXBmzX3ZZ8wHNChKR/FXh5LJPbCXAUCl686v3IaHf4JNP3mkgNZ7NRUKsJV0HXV2jl4Ag3lTDCp91HtZXoC7Nt6FzPnYaym6teGAG4kzviEdeHJmTn9yrXL7sGtYft88bkrB/XEDVIDjjYF57UeIl4ePKqMo/I9bTGb2/GZ2VHvi1wbgbriLZ0JD+6nhmYoXi02RzP5kOGquzpt+g0T3N80EgxiIOcFXe5svs75G0bRqyvuNLsk30KibwNB5ZUv5rjEu6AJNIrXp8vSqSnL6x/1CZO6dlA0RpaafxUv6GIi/COZ07YE3aUOrOI03P2DQWrdOTqgP3HW5zRhC6Q5tZU0bOmaiOUxYD2Lc+yn8+jIw+PIlBUfyQv+mTBZg81WxlwSwg6VIoo5ohu0JIF1gCSbjqnDW8aFL52YCQoJhjWrt54Jb0pLnbvjZc9/7eN1bOOLs9qADRlyEr4Mg7+aSF7B9l2IOuUT96do4x2i96cxPuxU="

branches:
  only:
    - sisyphus

#before_install:
#  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

install:
  - sudo apt-get install scons

script:
  - if [[ "${COVERITY_SCAN_BRANCH}" == 1 ]];
      then
        echo "Don't build on coverity_scan branch.";
        exit 0;
    fi
  - scons

addons:
  coverity_scan:
    project:
      name: "Etersoft/libnss-role"
      description: "NSS API library and admin tools for roles and privilegies"
    notification_email: lav@etersoft.ru
    build_command_prepend: 
    build_command: scons
    branch_pattern: sisyphus
