.TH ROLEADD "8" "" "" "libnss-role manual"
.SH NAME
roleadd \- Add new roles and add privileges for role
.SH SYNOPSIS
.B roleadd
[\fI-m\fR] [\fI-s\fR] \fIROLE \fR[\fIGROUP*\fR]\fR
.SH DESCRIPTION
roleadd is utility which allows to add privileges and groups to role groups.
This mean that all users at role and/or group get included to all
privileges and groups which are added to the modified role.
.SH OPTIONS
.TP
\fB\-h\fR [ \fB\-\-help\fR ]
produce help message
.TP
\fB\-s\fR [ \fB\-\-set\fR ]
set role with privileges
.TP
\fB\-m\fR [ \fB\-\-skip\-missed\fR ]
skipping for missed privilegies instead error
.TP
\fB\-v\fR [ \fB\-\-version\fR ]
print the version of roleadd being used
.SH "FEEDBACK"
Send bug reports and pull requests to
https://github.com/Etersoft/libnss-role
.SH "SEE ALSO"
.PP
.BR roledel (8),
.BR rolelst (8)
