.TH ROLEDEL "8" "" "" "libnss-role manual"
.SH NAME
roledel \- Remove roles and priviledges from role
.SH SYNOPSIS
.B roledel
[\fI-m\fR] \fIROLE \fR[\fIGROUP*\fR]\fR

.B roledel
[\fI-r\fR] \fIROLE\fR
.SH DESCRIPTION
roledel is an utility which allows to remove priviledges and groups from role groups.
This mean that all users at role group get excluded from all
privileges groups which are removed from the modified role.
.SH "OPTIONS"
.TP
\fB\-h\fR [ \fB\-\-help\fR ]
produce help message
.TP
\fB\-r\fR [ \fB\-\-remove\fR ]
remove role with all privilegies
.TP
\fB\-m\fR [ \fB\-\-skip\-missed\fR ]
skipping for missed privilegies instead error
.TP
\fB\-v\fR [ \fB\-\-version\fR ]
print the version of roledel being used
.SH "FEEDBACK"
Send bug reports and pull requests to
https://github.com/Etersoft/libnss-role
.SH "SEE ALSO"
.PP
.BR roleadd (8),
.BR rolelst (8)
