.TH ROLEDEL "18" "October 2010" "libnss_role" "Tartarus User's Manual"
.SH NAME
roledel \- Delete roles and remove priviledges from role
.SH SYNOPSIS
.B roledel
[\fI-m\fR] \fIROLE \fR[\fIGROUP*\fR]\fR

.B roledel
[\fI-r\fR] \fIROLE\fR
.SH DESCRIPTION
roledel is utility allows to remove priviledges groups from role groups.
This mean that all users at role group excludes from all
privileges groups which removed from modified role.
.SH "OPTIONS"
.TP
\fB\-h\fR [ \fB\-\-help\fR ]
produce help message
.TP
\fB\-r\fR [ \fB\-\-remove\fR ]
remove role with all privilegies
.TP
\fB\-m\fR [ \fB\-\-skip\-missed\fR ]
skipping for missed privilegies instead error
.TP
\fB\-v\fR [ \fB\-\-version\fR ]
print the version of roledel being used
.SH "SEE ALSO"
The full documentation for
.B roleadd
is maintained as part of documentation of
.B Tartarus
project available at:
.br
.BR http://tartarus.ru/projects/libnss-role
.PP
.BR roleadd (8),
.BR rolelst (8),
