.TH ROLELST "18" "October 2010" "libnss_role" "Tartarus User's Manual"
.SH NAME
rolelst \- Print list of roles and priviledge
.SH SYNOPSIS
.B rolelst
[\fIROLES*\fR]\fR
.SH DESCRIPTION
rolelst is utility prints current list of roles and privileges.
.SH OPTIONS
.TP
\fB\-h\fR [ \fB\-\-help\fR ]
produce help message
.TP
\fB\-v\fR [ \fB\-\-version\fR ]
print the version of rolelst being used
.SH "SEE ALSO"
The full documentation for
.B roleadd
is maintained as part of documentation of
.B Tartarus
project available at:
.br
.BR http://tartarus.ru/projects/libnss-role
.PP
.BR roleadd (8),
.BR roledel (8),
