.TH ROLELST "8" "" "" "libnss-role manual"
.SH NAME
rolelst \- Print list of roles and priviledges
.SH SYNOPSIS
.B rolelst
[\fIROLES*\fR]\fR
.SH DESCRIPTION
rolelst is utility prints current list of roles and privileges.
.SH OPTIONS
.TP
\fB\-h\fR [ \fB\-\-help\fR ]
produce help message
.TP
\fB\-v\fR [ \fB\-\-version\fR ]
print the version of rolelst being used
.SH "FEEDBACK"
Send bug reports and pull requests to
https://github.com/Etersoft/libnss-role
.SH "SEE ALSO"
.PP
.BR roleadd (8),
.BR roledel (8)
