#ifndef LIBROLE_GLOB_H
#define LIBROLE_GLOB_H

#define LIBROLE_STR_MIN_SIZE		100

#define LIBROLE_NO_SUCH_GROUP		-100
#define LIBROLE_OUT_OF_RANGE		-101
#define LIBROLE_MEMORY_ERROR		-102
#define LIBROLE_IO_ERROR		-103
#define LIBROLE_UNKNOWN_ERROR		-104
#define LIBROLE_OK			0

#endif
